version: 3

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      - PGUSER=user
      - PGPASSWORD=123456
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data